services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    networks:
      - app-network
 localstack:
   image: 'localstack/localstack:latest'
   ports:
     - '4566:4566'
     - '4510-4559:4510-4559'
   environment:
     - SERVICES=s3,sqs,sns
     - DEBUG=1
     - DOCKER_HOST=unix:///var/run/docker.sock
     - AWS_DEFAULT_REGION=us-east-1
     - AWS_ACCESS_KEY_ID=test
     - AWS_SECRET_ACCESS_KEY=test
   volumes:
     - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
     - '/var/run/docker.sock:/var/run/docker.sock'
   networks:
     - app-network

networks:
  app-network:
    driver: bridge
